import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <head>
        <title>FM Web Agency</title>
      </head>
      <body>
        <h1>FM WEB AGENCY</h1>
      </body>
    </html>
  );
}
